name: A build for node

on: 
  push:
    branches: [ main ]
jobs: 
  build:
   runs-on: macos-latest
   steps:
    - name: cloning a git repo
      uses: actions/checkout@v2

    - name: Setting up node
      uses: actions/setup-node@v1
      with:
          node-version: '16.x'
    - name: install dependencies
      run: npm install

    - name: ci on building and test
      run: npm run build
    
   
