name: A build for node

on: 
  push:
    branches: [ main ]
  pull-request:
    branches: [ main ]
jobs: 
build:
   runs-on: macos-latest
  step:
   -name: cloning a git repo
   uses: actions/checkout@v2
  step:
   -name: Setting up node
    uses: actions/setup-node@v1
    with:
      node-version: '16.x'
  step:
   -name: install dependencies
    run: npm install
  step:
   -run: npm run build
   -run: npm test
   
